cane:
  # gazebo_ros_control:
    # pid_gains:
      # back_left_wheel_hinge:
        # p: 1.0
        # i: 1.0
        # d: 0.1
      # back_right_wheel_hinge:
        # p: 1.0
        # i: 1.0
        # d: 0.1
      # front_left_wheel_hinge:
        # p: 1.0
        # i: 1.0
        # d: 0.1
      # front_right_wheel_hinge:
        # p: 1.0
        # i: 1.0
        # d: 0.1

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  shoulder_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.1, d: 1.0}