<?xml version="1.0" ?>
<robot name="cane" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="radius" value="0.01"/>
  <xacro:property name="offset" value="0.01"/>
  <xacro:property name="root2" value="1.41421356237"/> 
  <xacro:property name="pole_len" value="1.5"/> 
  <xacro:property name="pole_mass" value="0.1"/>
  <xacro:property name="arm_len" value="0.4"/>
  <xacro:property name="arm_deg" value="55"/>
  <xacro:property name="pole_offset" value="0.02"/>
  <xacro:property name="arm_radius" value="0.03"/>
  <xacro:property name="sensor_location" value="0.375"/>
  <xacro:property name="sensor_scan_vert_angle" value="30"/>
  <xacro:property name="sensor_scan_horiz_angle" value="30"/>
  <xacro:property name="sensor_fov_angle" value="30"/>
  <xacro:property name="sensor_cane_angle" value="30"/>


  <xacro:property name="arm_rad" value="${arm_deg * PI/180}"/>
  <xacro:property name="sensor_scan_vert_rad" value="${sensor_scan_vert_angle * PI/180}"/>
  <xacro:property name="sensor_scan_horiz_rad" value="${sensor_scan_horiz_angle * PI/180}"/>
  <xacro:property name="sensor_fov_rad" value="${sensor_fov_angle * PI/180}"/>
  <xacro:property name="sensor_cane_rad" value="${(90 - sensor_cane_angle) * PI/180}"/>
  <xacro:property name="base_height" value="${((pole_len + arm_len) * cos(arm_rad)) + pole_offset}"/>


  
  <xacro:include filename="$(find cane_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find cane_description)/urdf/cane.gazebo" />

  
  <link name="world" />

  <link name="arm_base" >
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${base_height}" radius="${arm_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <link name="shoulder"/>

  <link name="arm" >
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 ${-arm_len/2}" rpy="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>

    <visual>
      <origin xyz="0 0 ${-arm_len/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${arm_len}" radius="${arm_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>
  
  <link name="pole">
    <inertial>
      <mass value="${pole_mass}"/>
      <origin xyz="0 0 ${-pole_len/2}" rpy="0 0 0"/>
      <inertia ixx="1" ixy="0" ixz="0" iyy="1" iyz="0" izz="1"/>
    </inertial>
    
    <collision>
      <origin xyz="0 0 ${-pole_len/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pole_len}" radius="${radius}"/>
      </geometry>
    </collision>
    
    <visual>
      <origin xyz="0 0 ${-pole_len/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder length="${pole_len}" radius="${radius}"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <link name="imu_module"/>

  <link name="sensor_module"/>


  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="arm_base"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
  
  <joint name="shoulder_joint" type="continuous">
    <parent link="arm_base"/>
    <child link="shoulder"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/> 
  </joint>
  
  <joint name="arm_joint" type="fixed">
    <parent link="shoulder"/>
    <child link="arm"/>
    <origin xyz="0 0 0" rpy="0 ${-arm_rad} 0"/>
  </joint>

  <joint name="hand_joint" type="fixed">
    <parent link="arm"/>
    <child link="pole"/>
    <origin xyz="0 0 ${-arm_len}" rpy="0 0 0"/>
  </joint>

  <joint name="sensor_joint" type="fixed">
    <parent link="pole"/>
    <child link="sensor_module"/>
    <origin xyz="${radius + offset} 0 ${-sensor_location}" rpy="0 ${sensor_cane_rad} 0" />
  </joint>

  <joint name="imu_joint" type="fixed">
    <parent link="pole"/>
    <child link="imu_module"/>
    <origin xyz="${radius + offset} 0 ${-sensor_location}" rpy="0 ${sensor_cane_rad} 0" />
  </joint>


  <transmission name="cane_joint_trans">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="shoulder_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="cane_joint_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <gazebo reference="imu_module">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>/cane/imu</topicName>
        <bodyName>imu_module</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_module</frameName>
        <initialOrientationAsReference>false</initialOrientationAsReference>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

  <gazebo reference="sensor_module">
    <sensor type="ray" name="ultrasonic_ray">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>15</samples>
            <resolution>1.0</resolution>
            <min_angle>-${sensor_scan_horiz_rad/2}</min_angle>
            <max_angle>${sensor_scan_horiz_rad/2}</max_angle>
          </horizontal>
          <vertical>
            <samples>25</samples>
            <resolution>1.0</resolution>
            <min_angle>-${sensor_scan_vert_rad/2}</min_angle>
            <max_angle>${sensor_scan_vert_rad/2}</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>3</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <plugin name="gazebo_ros_range" filename="libgazebo_ros_range.so">
        <gaussianNoise>0.005</gaussianNoise>
        <alwaysOn>true</alwaysOn>
        <updateRate>30</updateRate>
        <topicName>/cane/sensor</topicName>
        <frameName>/sensor_module</frameName>
        <fov>${sensor_fov_rad}</fov>
        <radiation>ultrasound</radiation>
      </plugin>
    </sensor>
  </gazebo>
</robot>
